NAME=so_long

all: $(NAME)

$(NAME):
	 @#gcc main.c MLX42/libmlx42.a -lglfw -o $(NAME)
	 @#gcc main.c libmlx42.a -lglfw -L /opt/homebrew/Cellar/glfw/3.3.6/lib/
	 @gcc main.c MLX42/libmlx42.a -I include -lglfw -L "/Users/${USER}/.brew/opt/glfw/lib/"
	 @#gcc main.c MLX42/libmlx42.a -I include -lglfw -L "/Users/jre-gonz/.brew/Cellar/glfw/3.3.6/"
